### ISSUE TITLE
alternative implementation

### ISSUE THREAD

**Issue by stoeffel** [tshm/elm-doctest#13]
You might be interested in https://github.com/stoeffel/elm-doc-test. 
I used a different approach than you. It creates elm-tests from your doc-tests and you can run them using `node-test-runner`. It supports `{-`, multiline tests, you get nice compiler messages and because of it's dependency to elm-test you get nice assertion messages.

Please close this issue when you see it, it's not an bug. I just didn't know how to contact you differently. We might profit from each others work. Would be awesome to hear what you think of my approach. Hope it's okay that I opened this issue. Thanks for the inspiration.

### Screenshots

<details><summary>passing doc-test</summary>
<img width="1037" alt="screen shot 2016-11-29 at 10 50 56" src="https://cloud.githubusercontent.com/assets/1217681/20705060/d32a24aa-b621-11e6-915b-33258f5897fb.png">
</details>

<details><summary>failing doc-test</summary>
<img width="419" alt="screen shot 2016-11-29 at 10 51 25" src="https://cloud.githubusercontent.com/assets/1217681/20705061/d32bac58-b621-11e6-8647-0ac51d0781ad.png">
</details>

<details><summary>broken doc-test (doesn't compile)</summary>
<img width="1132" alt="screen shot 2016-11-29 at 10 51 11" src="https://cloud.githubusercontent.com/assets/1217681/20705059/d328e52c-b621-11e6-96e9-e322378808ea.png">
</details>

**Comment by tshm** [comment]
I love your work.  Thank you for letting me know your work.

Now I'm seriously thinking to close my project (by referring into your work) as
 your project seem better in many ways.
I hacked up my project because I wanted to use doctest but nothing was 
available at the moment, and open-sourced it so that some people may 
find value of doctest.

I love doctest and I use whenever I code with Haskell (the only one functional
 language I use other than Elm) as I think that
doctest works great with functional languages.
I'm glad find that at least some people feel the same way.

**Comment by stoeffel** [comment]
You're always welcome to collaborate on my project ❤️ . But to close your project wasn't my intention and I think you did a great job with this.

**Comment by stoeffel** [comment]
btw. I'm schtoeffel on twitter and stoffel on elmslack if you want to discuss stuff.
